# Generated by Django 4.1.5 on 2023-01-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('shortURL', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('targetURL', models.CharField(max_length=2083)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
